---
name: ''
title: nan winata dot me~
description: ''
logo: assets/images/logo_size_invert.jpg
favicon: assets/images/logo_size_invert.jpg
baseurl: ''
google_analytics: UA-140676015-1
disqus: nanwinata
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
authors:
  admin:
    name: admin
    display_name: nan
    gravatar: 15a751fea011039ca40cadc14e07a961
    email: nanwinata@gmail.com
    web: https://nanwinata.me
    twitter: https://twitter.com/enanwn
    description: Publisher, IT & Research Community
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
    category: "/category/:name/"
paginate: "10"
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
adsense: disabled
adsense-data-ad-client: ''
adsense-data-ad-slot: ''
lazyimages: disabled
exclude:
- vendor/bundle
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
